### PR TITLE
switch to npm

### PR DESCRIPTION
**Pull request by kellyselden**

### CODE REVIEW

**Comment by Turbo87** [comment]
:sob: why??

**Comment by kellyselden** [comment]
I'm trying to diagnose the differences. Yarn 1.7.0 is broken, but so is npm...

**Comment by Turbo87** [comment]
> Yarn 1.7.0 is broken

how so?

**Comment by kellyselden** [comment]
This line was causing issues https://github.com/kellyselden/ember-cli-rollup-packager/blob/fab6e891113b007c62e32362219bde72730b9a80/test/fixtures/my-app/package.json#L35 and there was a bug report for it, but now I can't reproduce. Strange.

**Pull request closed without merging**
